### ISSUE TITLE
无法找到和导入tactile_learning

### ISSUE THREAD

**Issue by BrightMoonStar** [dexterousrobot/tactile_gym#3]
无法找到和导入tactile_learning，似乎是丢失了
https://github.com/dexterousrobot/tactile_gym/blob/e4ac91eb5fe6f4ce3a3483b3a427d132a90cb054/tactile_gym/sb3_helpers/train_agent.py#L12C6-L12C22

**Comment by yijionglin** [comment]
Hi @BrightMoonStar 

Could you please share the error hint with us so that we can be more clear about what caused the problem.

Best,
Yijiong

**Comment by yijionglin** [comment]
@BrightMoonStar  I guess our [Beta version](https://github.com/yijionglin/tactile_gym/tree/Bi-Touch) should fix that problem. However, I am still merging the updated version with this current version with Nathan @nlepora.

You could play with our Beta version at the moment, and we will let you know once we finish merging it with the current version.

Best,
Yijiong

**Comment by TAO-TAO-TAO-TAO-TAO** [comment]
Hello, there is still no taxi available_ Learning module

**Comment by yuxwen** [comment]
Compile failed:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

Warning/Error in GLSL shader:
error: vertex shader lacks `main'

GL error 0x501 detected in glGenBuffers
ven = Mesa/X.org
ven = Mesa/X.org
Traceback (most recent call last):
File "/home/ros2/miniconda3/tactile_gym_push/tactile_gym/sb3_helpers/train_agent.py", line 184, in
train_agent(
File "/home/ros2/miniconda3/tactile_gym_push/tactile_gym/sb3_helpers/train_agent.py", line 52, in train_agent
env = make_training_envs(
File "/home/ros2/miniconda3/tactile_gym_push/tactile_gym/sb3_helpers/rl_utils.py", line 16, in make_training_envs
env = make_vec_env(env_id,
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/site-packages/stable_baselines3/common/env_util.py", line 105, in make_vec_env
return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 111, in init
observation_space, action_space = self.remotes[0].recv()
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 250, in recv
buf = self._recv_bytes()
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
buf = self._recv(4)
File "/home/ros2/miniconda3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
ven = Mesa/X.org

I am running the code on Ubuntu installed through a virtual machine. I wonder if this has any impact.
