### ISSUE TITLE
No module named 'tactile_sim'

### ISSUE THREAD

**Issue by CSSunYifeng** [dexterousrobot/tactile_gym#4]
Hello, I have a problem when I run `python examples/demo_env.py -env example_arm-v0 `
```
(tactile_gym) f91@ubuntu:~/workspace/tactile_gym$ python examples/demo_env.py -env example_arm-v0
pybullet build time: Nov 28 2023 23:51:11
Traceback (most recent call last):
  File "examples/demo_env.py", line 85, in <module>
    main()
  File "examples/demo_env.py", line 63, in main
    env = gym.make(
  File "/home/f91/anaconda3/envs/tactile_gym/lib/python3.8/site-packages/gym/envs/registration.py", line 581, in make
    env_creator = load(spec_.entry_point)
  File "/home/f91/anaconda3/envs/tactile_gym/lib/python3.8/site-packages/gym/envs/registration.py", line 61, in load
    mod = importlib.import_module(mod_name)
  File "/home/f91/anaconda3/envs/tactile_gym/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/f91/workspace/tactile_gym/tactile_gym/envs/example_envs/example_arm_env/example_arm_env.py", line 3, in <module>
    from tactile_sim.assets.default_rest_poses import rest_poses_dict
ModuleNotFoundError: No module named 'tactile_sim'
```

**Comment by yijionglin** [comment]
Hi @CSSunYifeng ,

Please download the tactile_sim repo from [here](https://github.com/dexterousrobot/tactile_sim).

Best,
Yijiong
